### ISSUE TITLE
Help spec needs to be moved into spec dir.

### ISSUE THREAD

**Issue by rondale-sc** [TampaRuby/turbot#28]
See title.

**Comment by rwjblue** [comment]
Looks like it is already in spec, or am I missing something stupid?

**Comment by rondale-sc** [comment]
It's in the spec dir.  Not in the plugins subdir even though its a plugin.  I'll close this soon.

**Comment by rwjblue** [comment]
Ahh, gotcha! Good catch!

**Comment by rondale-sc** [comment]
Closed by 29a5ef8f5439ae92b8a1e55145f65d9dc10183fb
