### ISSUE TITLE
Turbot should change his name when it's available again.

### ISSUE THREAD

**Issue by adamjleonard** [TampaRuby/turbot#34]
When turbot timeouts and reconnects, he doesn't have the nickname "turbot", but instead "turbot_" or something similar. Turbot should be able to check to see that his nickname has become available and then change it back to "turbot".

**Comment by pwelch** [comment]
Another option might be to see if Heroku has an option to restart the process.

**Comment by rwjblue** [comment]
Chain of events as follows:
1. turbot starts [see here](https://github.com/rondale-sc/turbot/blob/master/turbot.rb#L27)
2. Cinch::Bot creates a Cinch::IRC object and calls #start [see here](https://github.com/cinchrb/cinch/blob/master/lib/cinch/bot.rb#L272)
3. Cinch::IRC#start calls #send_login [see here](https://github.com/cinchrb/cinch/blob/master/lib/cinch/irc.rb#L207)
4. Cinch::IRC#send_login calls Cinch::Bot#generate_next_nick! [see here](https://github.com/cinchrb/cinch/blob/master/lib/cinch/irc.rb#L130)
5. If the nick is already taken IRC will raise a 433 error stating ERR_NICKNAMEINUSE [see here](http://www.irchelp.org/irchelp/rfc/chapter4.html#c4_1_2)
6. Cinch::IRC#parse calls Cinch::IRC#on_433 [here](https://github.com/cinchrb/cinch/blob/master/lib/cinch/irc.rb#L255)
7. Cinch::IRC#on_433 calls Cinch::Bot#generate_next_nick! passing in the nick that was attempted [here](https://github.com/cinchrb/cinch/blob/master/lib/cinch/irc.rb#L829)
8. Cinch::Bot#generate_next_nick! appends underscores until it finds an allowed name.

**Comment by rwjblue** [comment]
All of that crap being said, we can fix it by simply adding a timer to reclaim our nickname after a certain amount of time.
