### ISSUE TITLE
Move project?

### ISSUE THREAD

**Issue by pwelch** [TampaRuby/turbot#35]
Possibly move turbot project to [Tampa Ruby](https://github.com/TampaRuby) Organization?

**Comment by pwelch** [comment]
Need to transfer project to Tampa Ruby Organization account. It looks like we need to remove the fork of the project from Tampa Ruby as mentioned [here](https://help.github.com/articles/how-to-transfer-a-repository) because the account taking ownership can not have a fork.

@gstark or @ambethia can you kill the [forked turbot repo](https://github.com/TampaRuby/turbot) when you get a chance. 

I can manage redeploying the bot to heroku when it is done. If there is no preference on who's heroku account I can do it on mine. 

/cc @rondale-sc @rjackson

**Comment by ambethia** [comment]
And done!

**Comment by ambethia** [comment]
Once ownership is moved, I'll make sure you guys have commit bits.

**Comment by rwjblue** [comment]
Ok, good deal. 

@pwelch - Next steps?

Robert Jackson

-- twitter: rwjblue
-- github: rjackson

**Comment by pwelch** [comment]
@rjackson We need @rondale-sc  to go through the Transfer Ownership steps again for the repo.

**Comment by rondale-sc** [comment]
Moved
