### ISSUE TITLE
Remove Reddit Joke Command

### ISSUE THREAD

**Issue by pwelch** [TampaRuby/turbot#38]
The [Reddit Joke command](https://github.com/rondale-sc/turbot/blob/master/plugin/reddit_joke_cinch_plugin.rb) returns unwanted joke material. Everyone in the Tampa.rb channel agrees the command should be removed or replaced with another joke source.

**Comment by rwjblue** [comment]
Want me to just rip it out for now?

**Comment by rwjblue** [comment]
Sorry, hit send too early:

Want me to rip out the reddit joke's for now, and then we can decide what to do for joke material in the future?

**Comment by pwelch** [comment]
@rjackson Yeah, that sounds good to me.
